server:
  port: 8080

  servlet:
    context-path: /

  error:
    whitelabel:
      enabled: false

property:
  app:
    init: false

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update

  profiles:
    active: dev

  mvc:
    static-path-pattern: /api/cafe/img/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true

  data:
    rest:
      base-path: /api

security:
  token:
    issuer: security
    expired: 60
    refreshExpired: 360
    signing-key: MIDAS